apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-react
  template:
    metadata:
      labels:
        app: front-end-react
    spec:
      containers:
        - name: front-end-react-container
          image: louis44220/front-end-react:1.0.1
          ports:
            - containerPort: 3000
