name: Docker image build and push when created branch

on:
  push:
    branches:
      - "*"

jobs:
  push_images:
    if: startsWith(github.ref, 'refs/heads/') && startsWith(github.ref, 'refs/heads/v')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: louis44220/front-end-react
          - context: order-service
            image: louis44220/order-service
          - context: user-service
            image: louis44220/user-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push versioned images
        run: |
          docker build -t dockerhubloginname/${{ matrix.context }}:${{ github.ref }} .
          docker push dockerhubloginname/${{ matrix.context }}:${{ github.ref }}
